### PR TITLE
Add documentation for reference implementation

### PR DESCRIPTION
**Pull request by mgudemann**

### CODE REVIEW

**Comment by vantuz-subhuman** [comment]
Rendered spec: [non-integer-spec.pdf](https://github.com/input-output-hk/fm-ledger-rules/files/2945778/non-integer-spec.pdf)

Posting the link for the rendered file here, just so I can shamelessly use github as a free file-storage :trollface:

**Comment by dnadales** [comment]
We should add the permanent links to hydra to the README...

**Comment by vantuz-subhuman** [comment]
> We should add the permanent aliased links to hydra to the README...

This will be awesome, thank you, @dnadales! Cuz my PDFs are not canonical, I use a web-tool for rendering, so it might miss some magic added during the build (like revisions, etc).

**Comment by dnadales** [comment]
https://github.com/input-output-hk/fm-ledger-rules/issues/301 

:)

**Pull request merged**
