### PR TITLE
Add a pretty diagram of the fund movement from Berlin workshop.

### PR DESCRIPTION
**Pull request by nc6**

### CODE REVIEW

**Comment by kantp** [comment]
@nc6 Can you please add a signature to the commit, so that it can be merged?

Also, does this compile without complaints for you? I just checked out the branch (wanted to amend the commit, adding a signature), but I got an error `LaTeX Error: Option clash for package tikz`.

**Comment by kantp** [comment]
It does produce output though, and it looks nice! Thanks for adding this :)

**Comment by JaredCorduan** [comment]
@nc6 I added a commit to:

- removed the `arrows` and `positioning` options in the tikz import
- make the arrows bigger so that the arrow heads were more visible

If you like the changes I can fix the git signature and merge the picture. thanks again!

**Comment by nc6** [comment]
@JaredCorduan Go for it!

**Pull request merged**
